name: Metrics
on:
  schedule:
    - cron: "*/1 * * * *" # Runs every minute # Runs daily
  workflow_dispatch:             # Allows manual triggering
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICTOKEN }}

      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICTOKEN }}
          base: ""
          plugin_isocalendar: yes

      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICTOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: gnuplot, html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 28

      # - name: 🦑 Achievements
      #   if: ${{ success() || failure() }}
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: achievements.svg
      #     token: ${{ secrets.METRICTOKEN }}
      #     base: ""
      #     output_action: gist
      #     committer_gist: ${{ secrets.METRICTOKEN }}
      #     plugin_achievements: yes
      #     plugin_achievements_display: compact
      #     plugin_fortune: yes

      # - name: Contributors and sponsors
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.people.repository.svg
      #     token: ${{ secrets.METRICTOKEN }}
      #     base: ""
      #     template: repository
      #     repo: metrics
      #     plugin_people: yes
      #     plugin_people_types: contributors, stargazers, watchers, sponsors

      - name: Current year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.svg
          token: ${{ secrets.METRICTOKEN }}
          base: ""
          plugin_calendar: yes

      - name: Detailed display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICTOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: polyglot, stargazer, sponsor, deployer, member, maintainer, developer, scripter, packager, explorer, infographile, manager
