name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily
  workflow_dispatch:             # Allows manual triggering
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICTOKEN }}

      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICTOKEN }}
          base: ""
          plugin_isocalendar: yes

      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICTOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4

      - name: Contributors with contributions count
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.contributors.contributions.svg
          token: ${{ secrets.METRICTOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_contributors: yes
          plugin_contributors_contributions: yes

      - name: Contributors and sponsors
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.people.repository.svg
          token: ${{ secrets.METRICTOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_people: yes
          plugin_people_types: contributors, stargazers, watchers, sponsors

      - name: Current year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.svg
          token: ${{ secrets.METRICTOKEN }}
          base: ""
          plugin_calendar: yes

      - name: Detailed display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICTOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: sponsor, maintainer, octonaut
